### ISSUE TITLE
No permisson on MacOS

### ISSUE THREAD

**Issue by haringsrob** [zafarella/OSX-RAMDisk#39]
Hi,

This looks great, however, when using macos it has no permission to create the permission?

Regards,

**Comment by zafarella** [comment]
if you could be a bit specific, so I can mbe help? What permissions you are talking about?

**Comment by haringsrob** [comment]
When it is creating the ramdrive at the location specified in the file i have permission denied.

However, I changed the file to create the ramdisk in my personal folder: /Users/{username}/ramdisk and everything went fine.

For me this can be closed, but maybe update the readme or make the location configurable?

**Comment by zafarella** [comment]
Can you please post the OS version you use, looks like apple now wants permission on new versions.

**Comment by haringsrob** [comment]
MacOs Sierra that is.

**Comment by zafarella** [comment]
Sorry for delay. I will make updates whenever will switch to new OS version. Thanks for pointing out.

**Comment by awsp** [comment]
+1 got the same problem in macOS Sierra

Edit: 
After manually opening the disk properties and grant **everyone** to Read & Write everything now works.  I guess the new OS Sierra only uses System for read & write

**Comment by d1th** [comment]
This is the needed change in **startupRAMDiskandCacheMover.sh** for it to work on Mac OS Sierra. Change is based on previous comment by @haringsrob. 
Change:  `mount_point=/Volumes/ramdisk` to `mount_point="/Users/${USER}/ramdisk"`

@awsp does your change persist after rebooting or unmounting the ramdisk? Since it recreates the ramdisk every time it seemed to me it would reset those permissions as well.

**Comment by zafarella** [comment]
Thanks for advice, if somebody could confirm that it works with new
version. I don't have new version yet unfortunately to test things.

**Comment by d1th** [comment]
@zafarella I'm running MacOS Sierra and made the changes yesterday and everything seems to be functioning for Chrome (it's the only one I enabled since the rest of the cache moving options are not being used by me). You wrote the script in such a way that only changing `mount_point` should make the rest of the caching work through a ramdisk located in the homedir. 

Here are some terminal commands to illustrate the version I'm running and the correct working of ramdisk:
```
$ sw_vers -productVersion 
10.12.2

$ /usr/local/bin/startupRAMDiskandCacheMover.sh
umount: /Users/Dith/ramdisk: not currently mounted
Initialized /dev/rdisk2 as a 512 MB case-insensitive HFS Plus volume
Created RAM disk.
RAM disk hidden.
/Users/Dith/Library/Caches/Google/Chrome/Default -> /Users/Dith/ramdisk/Dith/Google/Chrome/Default
Google Caches Done!
RAM disk Job Completed.

$ df -h | grep ramdisk
Filesystem                  Size   Used  Avail Capacity iused      ifree %iused  Mounted on
/dev/disk2                 512Mi   12Mi  500Mi     3%      12 4294967267    0%   /Users/Dith/ramdisk

$ ls /Users/Dith/ramdisk/Dith/
Google
```
I hope it answers your question. To me it seems there's two approaches you can take: **1)** You move the ramdisk to the user homedir `/Users/${USER}/ramdisk` for all OSX versions or **2)** you write a procedure using `sw_vers -productVersion | cut -d '.' -f 1,2` (this strips the third digit from the version number, e.g. 10.12.2 gets outputted as 10.12) that puts it in /Volumes/ramdisk on versions below MacOS Sierra (10.2.x) and in the homedir for people running MacOS Sierra. I have not tested option **1)** since I do not have an older MacOS version at my disposable but I'm pretty sure it will work.

**Comment by zafarella** [comment]
@d1th  if u could review #45 please
